name: intl_phone_number_input
description: A simple and customizable flutter package on International Phone Number Input.
version: 0.5.2+2
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.3

  libphonenumber: ^1.0.2
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/flags/
